version: "3.9"

services:
  postgres:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PG_VERSION: 15.1.1.34
        PG_MAJOR: 15
        BARMAN_VERSION: 3.11.1